[package]
name = "bins"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
crossterm = "0.25.0"
itertools = "0.10.5"
rayon = "1.6.1"
termion = "2.0.1"
tui = "0.19.0"

[dev-dependencies]
rstest = "0.16.0"

[[bin]]
name = "filter"
path = "src/bin/tui/misc/filter/main.rs"
