[package]
name = "bins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
rayon = "1.6.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
trim-margin = "0.1.0"
tui = "0.19.0"
crossterm = "0.25.0"
termion = "2.0.1"
anyhow = "1.0.68"
thiserror = "1.0.38"

[[bin]]
name = "document-gatherer"
path = "src/bin/document_gatherer.rs"

[[bin]]
name = "bf"
path = "src/bin/tui/misc/filter/main.rs"

[[bin]]
name = "bb"
path = "src/bin/tui/project/build_tool_launcher/main.rs"
